#! /bin/bash

echo
echo
echo "----------------------------------<i> SCRIPTS----------------------------------"
echo "  adminchk    Checks the presence of administrative permissions and prompts for"
echo "              the administrator password if absent."
echo "  autocln     Automatically cleans your system."
echo "  autogrub    Automatically updates and installs GRUB into /dev/sda."
echo "  automen     Automatically cleans and optimizes your system."
echo "  autoupd     Automatically updates your Debian system."
echo "  calc        An expression evaluator and wannabe calculator."
echo "  maccln      Cleans junk created in removable disks by macOS."
echo "  repeat      Repeats EDENsh's welcoming introduction."
echo "  setupchk    Checks the presence of optional third-party programs."
echo "  TiTaTo      A game of Tic-Tac-Toe."
echo
echo "See \"MANUAL.TXT\" included in the package for more help."
echo "-------------------------------------------------------------------------------"